CREATE TYPE "tipo_rol" AS ENUM (
  'lector',
  'bibliotecario',
  'administrador',
  'auditor'
);

CREATE TYPE "estado_ejemplar" AS ENUM (
  'disponible',
  'prestado',
  'baja'
);

CREATE TYPE "estado_prestamo" AS ENUM (
  'activo',
  'en_mora',
  'devuelto'
);

CREATE TABLE "usuario" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "documento" varchar(20) UNIQUE NOT NULL,
  "nombres" varchar(100) NOT NULL,
  "apellidos" varchar(100) NOT NULL,
  "correo" varchar(150) UNIQUE NOT NULL,
  "telefono" varchar(20),
  "password_hash" varchar(255) NOT NULL,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "rol" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" integer UNIQUE NOT NULL,
  "tipo" tipo_rol NOT NULL
);

CREATE TABLE "lector" (
  "id_rol" integer PRIMARY KEY
);

CREATE TABLE "bibliotecario" (
  "id_rol" integer PRIMARY KEY,
  "id_administrador" integer
);

CREATE TABLE "administrador" (
  "id_rol" integer PRIMARY KEY
);

CREATE TABLE "auditor" (
  "id_rol" integer PRIMARY KEY
);

CREATE TABLE "libro" (
  "isbn" varchar(13) PRIMARY KEY,
  "titulo" varchar(200) NOT NULL,
  "autor" varchar(150) NOT NULL,
  "categoria" varchar(80),
  "anio_publicacion" integer,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "ejemplar" (
  "isbn" varchar(13) NOT NULL,
  "numero_ejemplar" integer NOT NULL,
  "estado" estado_ejemplar NOT NULL DEFAULT 'disponible',
  PRIMARY KEY ("isbn", "numero_ejemplar")
);

CREATE TABLE "prestamo" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_lector" integer NOT NULL,
  "isbn" varchar(13) NOT NULL,
  "numero_ejemplar" integer NOT NULL,
  "id_bibliotecario" integer NOT NULL,
  "fecha_prestamo" date NOT NULL,
  "fecha_esperada_devolucion" date NOT NULL,
  "estado" estado_prestamo NOT NULL DEFAULT 'activo'
);

CREATE TABLE "devolucion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_prestamo" integer UNIQUE NOT NULL,
  "id_bibliotecario" integer NOT NULL,
  "fecha_devolucion" date NOT NULL
);

COMMENT ON COLUMN "bibliotecario"."id_administrador" IS 'creado_por; nulo si es cuenta sembrada';

COMMENT ON COLUMN "prestamo"."fecha_esperada_devolucion" IS 'CHECK >= fecha_prestamo';

ALTER TABLE "rol" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lector" ADD FOREIGN KEY ("id_rol") REFERENCES "rol" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bibliotecario" ADD FOREIGN KEY ("id_rol") REFERENCES "rol" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "administrador" ADD FOREIGN KEY ("id_rol") REFERENCES "rol" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "auditor" ADD FOREIGN KEY ("id_rol") REFERENCES "rol" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bibliotecario" ADD FOREIGN KEY ("id_administrador") REFERENCES "administrador" ("id_rol") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ejemplar" ADD FOREIGN KEY ("isbn") REFERENCES "libro" ("isbn") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "prestamo" ADD FOREIGN KEY ("id_lector") REFERENCES "lector" ("id_rol") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "prestamo" ADD FOREIGN KEY ("isbn", "numero_ejemplar") REFERENCES "ejemplar" ("isbn", "numero_ejemplar") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "prestamo" ADD FOREIGN KEY ("id_bibliotecario") REFERENCES "bibliotecario" ("id_rol") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "devolucion" ADD FOREIGN KEY ("id_prestamo") REFERENCES "prestamo" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "devolucion" ADD FOREIGN KEY ("id_bibliotecario") REFERENCES "bibliotecario" ("id_rol") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bibliotecario" ADD FOREIGN KEY ("id_administrador") REFERENCES "bibliotecario" ("id_rol") DEFERRABLE INITIALLY IMMEDIATE;
