CREATE TYPE "estado_ejemplar" AS ENUM (
  'disponible',
  'prestado',
  'baja'
);

CREATE TYPE "estado_prestamo" AS ENUM (
  'activo',
  'en_mora',
  'devuelto'
);

CREATE TABLE "rol" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(30) UNIQUE NOT NULL
);

CREATE TABLE "usuario" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "documento" varchar(20) UNIQUE NOT NULL,
  "nombres" varchar(100) NOT NULL,
  "apellidos" varchar(100) NOT NULL,
  "correo" varchar(150) UNIQUE NOT NULL,
  "telefono" varchar(20),
  "password_hash" varchar(255) NOT NULL,
  "activo" boolean NOT NULL DEFAULT true,
  "id_rol" integer NOT NULL
);

CREATE TABLE "libro" (
  "isbn" varchar(13) PRIMARY KEY,
  "titulo" varchar(200) NOT NULL,
  "autor" varchar(150) NOT NULL,
  "categoria" varchar(80),
  "anio_publicacion" integer,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "ejemplar" (
  "isbn" varchar(13) NOT NULL,
  "numero_ejemplar" integer NOT NULL,
  "estado" estado_ejemplar NOT NULL DEFAULT 'disponible',
  PRIMARY KEY ("isbn", "numero_ejemplar")
);

CREATE TABLE "prestamo" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_lector" integer NOT NULL,
  "isbn" varchar(13) NOT NULL,
  "numero_ejemplar" integer NOT NULL,
  "id_bibliotecario" integer NOT NULL,
  "fecha_prestamo" date NOT NULL,
  "fecha_esperada_devolucion" date NOT NULL,
  "estado" estado_prestamo NOT NULL DEFAULT 'activo'
);

CREATE TABLE "devolucion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_prestamo" integer UNIQUE NOT NULL,
  "id_bibliotecario" integer NOT NULL,
  "fecha_devolucion" date NOT NULL
);

COMMENT ON COLUMN "rol"."nombre" IS 'lector | bibliotecario | administrador | auditor';

COMMENT ON COLUMN "prestamo"."id_lector" IS 'usuario con rol lector (se valida con trigger)';

COMMENT ON COLUMN "prestamo"."id_bibliotecario" IS 'usuario con rol bibliotecario (se valida con trigger)';

COMMENT ON COLUMN "prestamo"."fecha_esperada_devolucion" IS 'CHECK >= fecha_prestamo';

COMMENT ON COLUMN "devolucion"."id_bibliotecario" IS 'usuario con rol bibliotecario (se valida con trigger)';

ALTER TABLE "usuario" ADD FOREIGN KEY ("id_rol") REFERENCES "rol" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ejemplar" ADD FOREIGN KEY ("isbn") REFERENCES "libro" ("isbn") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "prestamo" ADD FOREIGN KEY ("id_lector") REFERENCES "usuario" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "prestamo" ADD FOREIGN KEY ("isbn", "numero_ejemplar") REFERENCES "ejemplar" ("isbn", "numero_ejemplar") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "prestamo" ADD FOREIGN KEY ("id_bibliotecario") REFERENCES "usuario" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "devolucion" ADD FOREIGN KEY ("id_prestamo") REFERENCES "prestamo" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "devolucion" ADD FOREIGN KEY ("id_bibliotecario") REFERENCES "usuario" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;
